config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'
  devise_for :users,  path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  

  resources :tests, only: :index do
     member do
      post :start
    end
  end


  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
        resources :questions, shallow: true, except: :index do
          resources :answers, shallow: true, except: :index
        end
    end
    resources :gists, only: :index
    resources :badges 
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      # post :gist
    end
  end

  resource :gist, only: :create

  resources :badges, only: :index


end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_test, only: %i[index create new]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = Question.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to [:admin, @question]
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question]
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to [:admin, @question.test]
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Вопрос не найден!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[index create new]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = Question.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to @question.test
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Вопрос не найден!'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question, test)
    if question.persisted?
      "Редактировать #{question.test.title} вопрос"
    else
      "Создать новый #{test.title} вопрос"
    end
  end
end

app/views/questions/_form.html.erb
<h3><%= question_header(@question, @test) %></h3> 
<%= form_with model: [@test, @question] do |form| %>
<%= render 'shared/errors', resource: @question %>
<p>
  <%= form.label :body %>
  <%= form.text_field :body, value: @question.body %>
</p>
<p><%= form.submit %></p>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
 <td><%= link_to 'Show', question_path(question) %></td> 
  <td><%= link_to 'Edit', edit_question_path(question) %></td> 
   <td>
        <%= link_to 'Delete', 
                    question_path(question),
                    method: :delete,
                    data:   { confirm: 'Are you shure?' } %>

      </td>
</tr>

app/views/questions/edit.html.erb
<h1>Редактирование  вопроса: <%= @question.body %> </h1>

<%= render 'form' %>
<%= link_to 'Back', @question.test %>

app/views/questions/show.html.erb
<p>
  <strong>Вопрос</strong>
  <%= @question.body %>
</p>

<h2>Answers</h2>

<%= link_to 'New answer', new_question_answer_path(@question) %>

<ol>
<%= render @question.answers %>
</ol>

<%= link_to 'Back', @question.test %>