config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'
  devise_for :users,  path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  

  resources :tests, only: :index do
     member do
      post :start
    end
  end


  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
        resources :questions, shallow: true, except: :index do
          resources :answers, shallow: true, except: :index
        end
    end
    resources :gists, only: :index
    resources :badges 
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      # post :gist
    end
  end

  resource :gist, only: :create

  resources :badges, only: :index


end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, presence: true

  RULES = %i[success_category success_on_first_try success_all_level].freeze
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to [:admin, @badge], notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
        
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.name %></td>
  <td class="align-middle">
    <%= image_tag 'kubok.png', :alt => "image", size: 100 %>
  </td>

  <td class="align-middle"><%= link_to t('admin.answers.answer.show'), admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('admin.answers.answer.edit'), edit_admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('admin.answers.answer.delete'), admin_badge_path(badge),
                                       method: :delete,
                                       data: { confirm: t('admin.answers.answer.del_confirm') } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <div class="form-group">
    <p>
      <%= form.label :name %>
      <%= form.select :name, options_for_select(Badge::RULES), prompt: true, class: "custom-select" %>
    </p>
    
    <p>
      <%= form.label :image %>
      <%= form.text_field :image %>
    </p>

    <p><%= form.submit class: "btn btn-primary" %></p>
<% end %>
</div>

app/views/admin/badges/edit.html.erb
<h1><%= t('.edit_title') %></h1>

<%= render 'form' %>
<%= link_to t('admin.answers.edit.back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-4"><h1><%= t('.header') %></h1></div>

  <div class="col-12"><%= link_to t('.new_badge'), new_admin_badge_path %>
    <%= render 'shared/errors', resource: @badge %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= t('.name') %></th>
        <th><%= t('.image') %></th>
        <th colspan="3"><%= t('tests.index.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <%= render @badges %>
      </tbody>
    </table>
  </div>
</div>