config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'
  devise_for :users,  path: :gurus, path_names: { sign_in: :login, sign_out: :logout}
  

  resources :tests, only: :index do
     member do
      post :start
    end
  end


  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
        resources :questions, shallow: true, except: :index do
          resources :answers, shallow: true, except: :index
        end
    end
    resources :gists, only: :index
    resources :badges 
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      # post :gist
    end
  end

  resource :gist, only: :create

  resources :badges, only: :index


end

app/models/answer.rb
class Answer < ApplicationRecord
  LIMIT_ANSWERS = 4

  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_limit_answers

  private

  def validate_limit_answers
    errors.add(:answers_quantity, 'Ответов не должно быть больше 4') if question.answers.count >= LIMIT_ANSWERS
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to [:admin, @answer], notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question]
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to @answer, notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to t('.show'), admin_answer_path(answer) %> |
  <%= link_to t('.edit'), edit_admin_answer_path(answer) %> |
   <%= link_to t('.delete'), 
                    admin_answer_path(answer),
                    method: :delete,
                    data:   { confirm: t('.del_confirm') } %>

</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer] do |form| %>
<%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p><br>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.header') %></h1>

<p>
<%= @answer.question.body %>
</p>

<%= render 'form' %>

<%= link_to t('.back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1><%= t('.header') %></h1>
<p>
<%= @question.body %>
</p>

<%= render 'form' %>

<%= link_to t('admin.answers.edit.back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.header') %></h1>
<p>
<%= @answer.question.body %>
</p>

<p>
<b><%= t('.answer') %></b>
<%= @answer.body %>
</p>

<p>
<b><%= t('.correct') %></b>
<%= @answer.correct %>
</p>

<%= link_to t('admin.answers.edit.back'), admin_question_path(@answer.question) %>